name: earthquake_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  dashed_circular_progress_bar: ^0.0.4
  firebase_auth: ^4.17.0
  firebase_core: 2.27.0
  firebase_database: ^10.4.9
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.0
  image_picker: ^1.0.8
  latlong2: ^0.9.1
  multi_circular_slider: ^1.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  quickalert: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  sqflite: any

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
